
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - containers.ovhcloud.com
  resources:
  - databaseauthorizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containers.ovhcloud.com
  resources:
  - databaseauthorizations/status
  verbs:
  - get
  - patch
  - update
