apiVersion: containers.ovhcloud.com/v1alpha1
kind: DatabaseAuthorization
metadata:
  name: databaseauthorization-sample
spec:
  ovhServices:
    - ks123-ovh
  ovhCredentials:
    token:
      name: ovh-credentials
      namespace: default
    application:
      name: ovh-credentials
      namespace: default
  labelSelector:
    matchLabel: []